import type { BanquetVenue, Hotel } from '../types.ts'
import { BANQUETS, inr } from './hotels.ts'
import { FOUNDED_YEAR, PROPERTY_COUNT, QUADIS_PHONE } from './site.ts'

/**
 * One source of truth for every page's <title> and meta description.
 *
 * WHY this file exists at all — the client's SEO person, WhatsApp 4 Aug 2026:
 * "SEO k liye mujhe meta tags dalne, lkin isme same he code hr landing page me
 * h. To koi solution h us cheez ka aage" ("I need to add meta tags for SEO, but
 * the same code is on every landing page. Is there a solution for that going
 * forward?").
 *
 * Two things were true when she wrote that, and only one of them is fixable
 * here:
 *
 *  1. Every page DID already pass its own title and description to <Seo>. What
 *     it did not have was a single place to read or edit them — the copy was
 *     scattered across nineteen page components, so "the same code on every
 *     landing page" is exactly what she saw when she opened them. That is what
 *     this file fixes: she can now be pointed at ONE file, and a page component
 *     carries `<Seo {...pageSeo('/contact')} />` and nothing else.
 *  2. The site is a client-rendered SPA. `view-source:` on any URL returns
 *     index.html, whose head is identical for all 25 routes, because <Seo>
 *     writes into the DOM only after React mounts. Nothing in this file can
 *     change that — it needs prerendering or SSR at build/edge time. See
 *     the note in src/components/Seo.tsx.
 *
 * Rule for anyone editing this: hotel and banquet copy is TEMPLATED from
 * src/data/hotels.ts, never written out per property. A tenth hotel added to
 * STATIC_HOTELS must arrive with correct meta, a sitemap entry and a canonical
 * URL without anybody touching this file.
 */

export const SITE_NAME = 'Quadis Hotels'

/**
 * The brand exactly as the client writes it in her own copy (feedback PDF,
 * 5 Aug 2026). Titles she supplies end with this, not with SITE_NAME, and the
 * suffix logic in Seo.tsx has to recognise both — otherwise her home-page title
 * ships as "… | Quadis Group of Hotels | Quadis Hotels".
 */
export const BRAND_LEGAL_NAME = 'Quadis Group of Hotels'

/**
 * www, not the bare apex, and it must stay in step with ORIGIN in
 * scripts/generate-sitemap.mjs. The client's live site is canonical on
 * https://www.quadishotels.com and the apex 301s to it, so an apex canonical
 * tag points every page at a redirect and splits signals across two hostnames —
 * against a sitemap that already declares www. This constant used to read
 * `https://quadishotels.com`, i.e. the canonical tag and the sitemap disagreed
 * on every one of the 25 URLs. Verified off the live host 30 Jul 2026.
 */
export const SITE_ORIGIN = 'https://www.quadishotels.com'

/**
 * Fallback link-preview image. `/images/home/hero.jpg` — the path this used to
 * point at — does not exist and never has: the file on disk is hero.webp, so
 * every page that did not pass its own `image` advertised a 404 to WhatsApp,
 * Facebook and LinkedIn. Files under public/ are copied to the dist root
 * verbatim by Vite, so this literal path is correct in production too.
 */
export const DEFAULT_OG_IMAGE = '/images/home/hero.webp'

/** Props <Seo> accepts. Kept here so page components import from one module. */
export interface SeoMeta {
  title: string
  description: string
  image?: string
  ogType?: string
  noIndex?: boolean
  canonicalPath?: string
}

export interface PageMeta extends SeoMeta {
  /**
   * Crawl priority for this route in sitemap.xml, or null to keep it out of
   * the sitemap entirely (auth and account pages, which also carry noIndex).
   *
   * It lives HERE rather than in the sitemap script on purpose: the two lists
   * were maintained separately, so a route could be given meta and quietly
   * never be submitted, or be submitted with no meta. generate-sitemap.mjs now
   * reads this file, and the two cannot drift.
   */
  sitemapPriority: string | null
}

/**
 * Every static route in App.tsx. Hotel and banquet detail pages are NOT here —
 * they are generated by hotelSeo()/banquetSeo() below.
 *
 * Copy rules applied throughout, and worth keeping to when adding a route:
 *
 *  - The distinctive words come first. Search results and browser tabs both
 *    truncate from the right, and Seo.tsx appends "| Quadis Hotels" to the end,
 *    so the brand is what gets cut — deliberately.
 *  - Titles stay inside ~63 characters BEFORE that suffix, descriptions inside
 *    160. Checked across all 25 routes on 5 Aug 2026.
 *  - No two routes share a title or a description. That was the whole of the
 *    client's complaint, so it is the one property that must not regress.
 *  - Use the locality names she actually sells against — Lajpat Nagar, East of
 *    Kailash, New Ashok Nagar, Noida — not the generic "Delhi NCR" alone.
 */
const STATIC_PAGE_SEO = {
  /*
   * Home. VERBATIM from the client's feedback PDF, page 1, 5 Aug 2026 — she
   * supplied both strings and they are not to be "improved". Note the title
   * already carries her brand lockup, which is why Seo.tsx has to recognise
   * "Quadis Group of Hotels" as a brand suffix and not append a second one.
   */
  '/': {
    title: 'Best Budget hotels in Delhi & Noida | Quadis Group of Hotels',
    description:
      'Book budget-friendly hotel rooms in Delhi NCR at Quadis offering comfort and great connectivity near Lajpat Nagar, East of Kailash, New Ashok Nagar, and Noida.',
    sitemapPriority: '1.0',
  },

  '/hotels': {
    title: `All ${PROPERTY_COUNT} Quadis Hotels in Noida & New Delhi`,
    description: `Compare all ${PROPERTY_COUNT} Quadis properties side by side — Lajpat Nagar, East of Kailash and Noida sectors 15, 19, 27 and 51. Tariffs, guest ratings and metro distances.`,
    sitemapPriority: '0.9',
  },

  '/banquets': {
    title: 'Banquet Halls in Lajpat Nagar, East of Kailash & Noida',
    description: `${BANQUETS.length} Quadis banquet halls for weddings, receptions and corporate events — 40 to 80 guests, in-house veg and non-veg catering, valet and on-site parking.`,
    sitemapPriority: '0.8',
  },

  // Existing copy, kept. It was already specific and non-duplicated; the brief
  // was coverage and distinctness, not churn.
  '/restaurant': {
    title: 'Restaurant & In-House Dining',
    description:
      'Multi-cuisine in-house kitchens serving breakfast spreads, room dining and customised event menus across Quadis Hotels.',
    sitemapPriority: '0.7',
  },

  '/restaurant/outdoor-catering-service': {
    title: 'Outdoor Catering Service in Delhi NCR',
    description:
      'Customised outdoor catering from the Quadis kitchens — multi-cuisine menus for weddings, corporate events and private gatherings across Delhi NCR.',
    sitemapPriority: '0.6',
  },

  '/corporate-hotel-booking': {
    title: 'Corporate Hotel Booking in Delhi NCR',
    description:
      'Negotiated corporate rates, priority availability and consolidated GST-compliant billing across every Quadis property in Delhi NCR.',
    sitemapPriority: '0.7',
  },

  // "About Us" as a title ranks for nothing and reads identically to every
  // other hotel group's about page. The founding year and property count both
  // come from src/data/site.ts, so this line stays true as the group grows.
  '/about-us': {
    title: `About Quadis Group of Hotels — Delhi NCR Since ${FOUNDED_YEAR}`,
    description: `From a single property in ${FOUNDED_YEAR} to ${PROPERTY_COUNT} across Delhi and Noida. How Quadis runs budget hotels that still feel considered, and the people who look after your stay.`,
    sitemapPriority: '0.5',
  },

  '/gallery': {
    title: 'Photo Gallery — Rooms, Banquet Halls & Dining',
    description: `Deluxe rooms, super deluxe rooms, royal suites, facades, lobbies and banquet halls photographed across all ${PROPERTY_COUNT} Quadis properties in Delhi and Noida.`,
    sitemapPriority: '0.5',
  },

  '/virtual-tour': {
    title: '360° Virtual Tour of Our Delhi & Noida Hotels',
    description:
      'Walk through a Quadis room, lobby and banquet hall before you book — a 360-degree tour of the group’s properties across Delhi NCR, with live tariffs.',
    sitemapPriority: '0.5',
  },

  // The reservations number is the whole point of this page, so it belongs in
  // the snippet where a searcher can act on it without clicking through.
  '/contact': {
    title: 'Contact Quadis Hotels — Reservations & Enquiries',
    description: `Call the Quadis reservations desk on ${QUADIS_PHONE}, or send an enquiry for room bookings, banquet dates and corporate rates across Noida and New Delhi.`,
    sitemapPriority: '0.6',
  },

  /*
   * The three legal pages. Low priority but they must be indexed: Razorpay
   * requires them reachable before it approves the merchant account, and the
   * client's existing site has /privacy-policy and /terms-and-conditions
   * indexed today. `canonicalPath` is pinned rather than taken from
   * useLocation() because these are the URLs already in Google's index.
   */
  '/privacy-policy': {
    title: 'Privacy Policy — How We Handle Your Data',
    description:
      'What Quadis Hotels collects when you browse, book or enquire, how long it is kept, who it is shared with, and how to ask us to delete it.',
    canonicalPath: '/privacy-policy',
    sitemapPriority: '0.3',
  },

  '/terms-and-conditions': {
    title: 'Terms & Conditions — Reservations & Stays',
    description:
      'The terms you agree to when you reserve with Quadis Hotels: check-in and check-out, ID requirements, occupancy, payment and conduct during your stay.',
    canonicalPath: '/terms-and-conditions',
    sitemapPriority: '0.3',
  },

  '/cancellation-policy': {
    title: 'Cancellation & Refund Policy',
    description:
      'Cancellation windows, refund timelines and no-show charges for direct bookings made with Quadis Hotels, including how refunds are returned to your card.',
    canonicalPath: '/cancellation-policy',
    sitemapPriority: '0.3',
  },

  /*
   * Below this line: routes deliberately kept OUT of the index. They still need
   * meta — <Seo> writes `robots: noindex` on every route precisely so the tag
   * cannot leak from /account onto /hotels — but `sitemapPriority: null` keeps
   * them out of sitemap.xml, which must agree with robots.txt.
   */
  '/login': {
    title: 'Sign In',
    description: 'Sign in to your Quadis Hotels account to view and manage your bookings.',
    noIndex: true,
    sitemapPriority: null,
  },

  '/register': {
    title: 'Create an Account',
    description: 'Create a Quadis Hotels account to book faster and keep your reservations in one place.',
    noIndex: true,
    sitemapPriority: null,
  },

  '/account': {
    title: 'My Account',
    description: 'View and manage your Quadis Hotels bookings.',
    noIndex: true,
    sitemapPriority: null,
  },

  // The 404 has no path of its own — it answers on whatever URL was missed, so
  // canonicalPath is deliberately absent and useLocation() supplies it.
  '/404': {
    title: 'Page Not Found',
    description:
      'The page you are looking for does not exist. Browse our hotels across Noida and New Delhi instead.',
    noIndex: true,
    sitemapPriority: null,
  },
} satisfies Record<string, PageMeta>

export type StaticSeoPath = keyof typeof STATIC_PAGE_SEO

/**
 * Meta for a static route, ready to spread onto <Seo>.
 *
 * The route path doubles as the canonical path, so /hotels?city=Noida and
 * /hotels?city=New%20Delhi cannot present as two indexable URLs with identical
 * copy. Entries that pin their own canonicalPath (the legal pages) win.
 */
export function pageSeo(path: StaticSeoPath): SeoMeta {
  const meta: PageMeta = STATIC_PAGE_SEO[path]
  return {
    title: meta.title,
    description: meta.description,
    image: meta.image,
    ogType: meta.ogType,
    noIndex: meta.noIndex,
    canonicalPath: meta.canonicalPath ?? (path === '/404' ? undefined : path),
  }
}

/* ------------------------------------------------------------------------- *
 * Templated meta: hotels and banquets
 * ------------------------------------------------------------------------- */

/**
 * Several property names already contain their own area or city — "Hotel
 * Downtown Sector 15 Noida" carries both — while others carry neither ("Hotel
 * Amar Inn"). Appending unconditionally produced "Hotel Downtown Sector 15
 * Noida, Sector 15, Noida", which reads like a broken template and wastes the
 * ~60 characters Google actually shows. So each part is added only if the name
 * is not already saying it.
 */
const appendIfMissing = (base: string, part: string): string =>
  base.toLowerCase().includes(part.toLowerCase()) ? base : `${base}, ${part}`

/**
 * Meta for one hotel landing page, derived entirely from src/data/hotels.ts.
 *
 * The title leads with the property and its locality because that is how guests
 * search ("hotel in sector 51 noida", "budget hotel lajpat nagar"), and the
 * description carries the three facts that decide a click on a budget booking:
 * where it is relative to the metro, the nightly rate, and the guest rating.
 *
 * `image` is passed in rather than derived: the page already resolves its
 * photography through the Vite asset glob, which hashes filenames, so there is
 * no stable public path this module could guess.
 */
export function hotelSeo(hotel: Hotel, image?: string): SeoMeta {
  const place = appendIfMissing(hotel.name, hotel.area)

  // If the name or area already said "Noida", saying it a third time in the
  // same title is spam, not signal — and it costs characters the title cannot
  // spare. Every generated title stays inside ~63 characters before the brand
  // suffix, which is roughly where Google's results page starts truncating.
  const qualifier = place.toLowerCase().includes(hotel.city.toLowerCase())
    ? 'Budget Rooms & Tariff'
    : `Budget Hotel in ${hotel.city}`

  const metro = hotel.transit?.metro
  const near = metro ? ` — ${metro.value} from ${metro.name}` : ''

  return {
    title: `${place} — ${qualifier}`,
    description: `Budget rooms at ${hotel.name} in ${hotel.area}, ${hotel.city}${near}. From ${inr(hotel.price)} a night, rated ${hotel.rating.toFixed(1)}/5. Book direct.`,
    image,
    canonicalPath: `/hotels/${hotel.slug}`,
  }
}

/**
 * Meta for one banquet landing page, derived entirely from BANQUETS.
 *
 * Leads with "Banquet Hall in <area>, <city>" because the search that matters
 * here is the locality one, not the brand one — nobody types "Banquets at Hotel
 * Amby Inn" into Google. The property name follows so the two Delhi venues stay
 * distinguishable in a results page.
 *
 * Capacities are the client's own figures (feedback, 5 Aug 2026), so a snippet
 * promising 65 guests is a number she stands behind.
 */
export function banquetSeo(venue: BanquetVenue, image?: string): SeoMeta {
  const property = venue.name.replace(/^Banquets at\s+/i, '')

  return {
    title: `Banquet Hall in ${venue.area}, ${venue.city} — ${property}`,
    description: `${property}’s banquet hall in ${venue.area}, ${venue.city} seats up to ${venue.capacity} guests across ${venue.hallArea}, with ${venue.catering.toLowerCase()} catering and ${venue.parking.toLowerCase()}.`,
    image,
    canonicalPath: `/banquets/${venue.slug}`,
  }
}
